.PHONY: run generate clean

# Run the application from the root folder
run:
	cd app && go run main.go

# Generate gRPC code for cpu system usage and cpu user usage
generate:
	protoc --proto_path=proto \
	    --go_out=app/usecases/cpu/get_cpu_system_usage/grpc/proto \
	    --go-grpc_out=app/usecases/cpu/get_cpu_system_usage/grpc/proto \
	    --go_opt=paths=source_relative \
	    --go-grpc_opt=paths=source_relative \
	    proto/get_cpu_system_usage.proto

	protoc --proto_path=proto \
	    --go_out=app/usecases/cpu/get_cpu_user_usage/grpc/proto \
	    --go-grpc_out=app/usecases/cpu/get_cpu_user_usage/grpc/proto \
	    --go_opt=paths=source_relative \
	    --go-grpc_opt=paths=source_relative \
	    proto/get_cpu_user_usage.proto

	mkdir -p app/proto/get_full_prometheus_data # Create the output directory if it doesn't exist inside app
	protoc --proto_path=proto \
		--go_out=app/proto/get_full_prometheus_data \
		--go-grpc_out=app/proto/get_full_prometheus_data \
		--go_opt=paths=source_relative \
		--go-grpc_opt=paths=source_relative \
		proto/get_full_prometheus_data.proto	

# Clean autogenerated files if needed
clean:
	rm -f app/usecases/cpu/get_cpu_system_usage/grpc/proto/*.pb.go
	rm -f app/usecases/cpu/get_cpu_user_usage/grpc/proto/*.pb.go
